import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Body from '../../components/Body/Body';
import Header from '../../components/Header/Header';
import Techstack from '../../components/Techstack/Techstack';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Body />
        <Techstack />
      </main>
    </>
  );
}
